<a href="https://www.kaggle.com/code/sagorkumarmitra/pytorch-operations?scriptVersionId=194311765" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.4.0+cpu'

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.dtype

dtype('int64')

In [6]:
type(arr)

numpy.ndarray

In [7]:
 x = torch.from_numpy(arr)

In [8]:
x

tensor([1, 2, 3, 4, 5])

In [9]:
type(x)

torch.Tensor

In [10]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [11]:
x.dtype

torch.int64

In [12]:
arr2d = np.arange(0.0,12.0)

In [13]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [14]:
arr2d = arr2d.reshape(4,3)

In [15]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [16]:
x2 = torch.from_numpy(arr2d)

In [17]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [18]:
my_arr = np.arange(0,10)

In [19]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_tensor = torch.tensor(my_arr)

In [21]:
my_other_tensor = torch.from_numpy(my_arr)

In [22]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_arr[9] = 9999

In [24]:
my_arr

array([   0,    1,    2,    3,    4,    5,    6,    7,    8, 9999])

In [25]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
my_other_tensor

tensor([   0,    1,    2,    3,    4,    5,    6,    7,    8, 9999])

In [27]:
new_arr = np.array([1,2,3])

In [28]:
new_arr.dtype

dtype('int64')

In [29]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [30]:
torch.Tensor(new_arr)

tensor([1., 2., 3.])

In [31]:
torch.empty(2,2)

tensor([[ 1.7166e-09,  4.5649e-41],
        [-3.9479e-37,  3.1681e-41]])

In [32]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [33]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [34]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [35]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [36]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [37]:
my_tensor = torch.tensor([1,2,3])

In [38]:
my_tensor.dtype

torch.int64

In [39]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [40]:
my_tensor.dtype

torch.int64

In [41]:
torch.rand(4,3)

tensor([[0.8189, 0.4859, 0.3019],
        [0.0593, 0.1904, 0.3041],
        [0.0542, 0.3554, 0.1046],
        [0.5763, 0.6217, 0.0911]])

In [42]:
torch.randn(4,3)

tensor([[ 2.2293,  1.7676,  0.1822],
        [ 0.1146,  0.1436,  0.8167],
        [-0.9493,  0.6860, -0.9441],
        [ 0.0609, -1.3530,  1.4036]])

In [43]:
torch.randint(low=0,high=10,size=(5,5))

tensor([[7, 2, 4, 7, 9],
        [7, 8, 7, 2, 6],
        [6, 2, 6, 2, 0],
        [8, 8, 7, 7, 5],
        [1, 7, 0, 8, 7]])

In [44]:
x = torch.zeros(2,5)

In [45]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [46]:
x.shape

torch.Size([2, 5])

In [47]:
torch.rand_like(x)

tensor([[0.9219, 0.7037, 0.0852, 0.2514, 0.6914],
        [0.4550, 0.9228, 0.9157, 0.3819, 0.6303]])

In [48]:
torch.randn_like(x)

tensor([[ 0.6452,  0.4933, -1.3003,  0.6237, -1.3625],
        [ 0.0767,  0.6539,  0.7073,  1.6125,  0.8049]])

In [49]:
torch.randint_like(x,low=0,high=11)

tensor([[ 7.,  1.,  1.,  9.,  3.],
        [ 6., 10.,  9.,  6., 10.]])

In [50]:
torch.manual_seed(42)

torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [51]:
x= torch.arange(6).reshape(3,2)

In [52]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [53]:
x[1,1]

tensor(3)

In [54]:
x[:,1]

tensor([1, 3, 5])

In [55]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [56]:
x = torch.arange(10)

In [57]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [59]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [60]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
x = torch.arange(10)

In [62]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
x.shape

torch.Size([10])

In [64]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [65]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [66]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [67]:
a

tensor([1., 2., 3.])

In [68]:
b

tensor([4., 5., 6.])

In [69]:
a * b

tensor([ 4., 10., 18.])

In [70]:
torch.add(a,b)

tensor([5., 7., 9.])

In [71]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [72]:
a

tensor([ 4., 10., 18.])

In [73]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [74]:
a 

tensor([1., 2., 3.])